FROM node:22-alpine

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

RUN pnpm prisma generate
RUN pnpm build

ENV PORT=3000
ENV BASE_URL=http://localhost:3000
ENV DEFAULT_PICTURE_URL=http://localhost:3000/public/images/defaultuser.jpg

ENV LOGGER_TRANSPORT=console
ENV LOGGER_LEVEL=http

EXPOSE 3000

CMD ["npm", "run", "start:prod"]
